######################## default configuration ####################
#baseURL = "https://demo.gethugothemes.com/educenter/examplesite/"
baseURL = "https://www.ppmedenhaag.nl"


title = "PPME Den Haag"
#theme = "educenter-hugo-not-used"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "ppme-demo-002" # get your shortname form here : https://disqus.com


defaultContentLanguage = "nl"

pluralizelisttitles = false

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "PPME Den Haag"
author = "PPME Den Haag IT Team"
# contact info
address = "Medlerstraat 4, 2531 HA Den Haag"
#mobile = "+31-to-be-confirmed"
#phone_komisi_jenazah = "0682688948"
email = "info@ppmedenhaag.nl"
# contact form action
contact_form_action = "https://formspree.io/f/mvolqyea" # contact form works with https://formspree.io
#contact_form_action = "https://formspree.io/f/mknyzkkn" # contact form works with https://formspree.io
#contact_form_action = "https://submit-form.com/rPJDglWY" # contact form works with https://submit-form.com
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
#map_latitude = "51.5223477"
#map_longitude = "-0.1622023"
#map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "https://www.facebook.com/PPMEcabDenHaag/"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"
